version: '3'
services:
  database:
    image: postgres
    container_name: psql-container
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
  app:
    build: .
    command: ["./wait-for-postgres.sh", "postgres://postgres:postgres@database:5432/postgres", "npm", "run", "start"]
    container_name: node-container
    ports:
      - "8080:8022"
    environment:
      - PORT=8022
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
    depends_on: 
      - database
    networks:
      - my-network

networks:
  my-network:
    driver: bridge 
